import express from 'express';
import productRouter from './product.js';
import routerCategory from './category.js';
import cartRouter from './cart.js';
import invoiceRouter from './invoice.js';
const router = express.Router();
router.use('/cart', cartRouter);
router.use('/product', productRouter);
router.use('/invoice',invoiceRouter);
router.use('/category', routerCategory);
export default router;